{
 "title": "Admin Apps Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "admin_apps",
    "query": "flux,flux-helm-operator,sealed-secrets,traefik"
   }
  ]
 },
 "panels": [
  { "title": "Admin Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "${admin_apps}",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "repeat": "admin_apps",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"admin\",deployment=\"${admin_apps}\"}/kube_deployment_spec_replicas{namespace=\"admin\",deployment=\"${admin_apps}\"}*100"
    }
   ]
  },
  {
   "title": "Tunnelfront",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"kube-system\",deployment=\"tunnelfront\"}/kube_deployment_spec_replicas{namespace=\"kube-system\",deployment=\"tunnelfront\"}*100"
    }
   ]
  },
  {
   "title": "Neuvector Controller",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"neuvector\",deployment=\"neuvector-controller-pod\"}/kube_deployment_spec_replicas{namespace=\"neuvector\",deployment=\"neuvector-controller-pod\"}*100"
    }
   ]
  },
  {
   "title": "Neuvector Enforcer",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{namespace=\"neuvector\",daemonset=\"neuvector-enforcer-pod\"}/kube_daemonset_status_desired_number_scheduled{namespace=\"neuvector\",daemonset=\"neuvector-enforcer-pod\"}*100"
    }
   ]
  },
  {
   "title": "Traefik IP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "kube_service_status_load_balancer_ingress{service=\"traefik\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  }
 ]
}