{
 "title": "Applications Health Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "ReferenceData Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "RD Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"rd\"}/kube_deployment_spec_replicas{namespace=\"rd\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "IDAM Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "IDAM Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"idam\"}/kube_deployment_spec_replicas{namespace=\"idam\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CCD Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "CCD Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"ccd\"}/kube_deployment_spec_replicas{namespace=\"ccd\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Divorce Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Divorce Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"divorce\"}/kube_deployment_spec_replicas{namespace=\"divorce\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Probate Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Probate Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"probate\"}/kube_deployment_spec_replicas{namespace=\"probate\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CMC Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "MoneyClaims Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"money-claims\"}/kube_deployment_spec_replicas{namespace=\"money-claims\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "IA Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "IA Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"ia\"}/kube_deployment_spec_replicas{namespace=\"ia\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "UCMC Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "UCMC Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"ucmc\"}/kube_deployment_spec_replicas{namespace=\"ucmc\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ReformScan Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "RreformScan Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"reform-scan\"}/kube_deployment_spec_replicas{namespace=\"reform-scan\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Financial Remedy Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "financial-remedy Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"financial-remedy\"}/kube_deployment_spec_replicas{namespace=\"financial-remedy\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "BSP Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "BSP Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"bsp\"}/kube_deployment_spec_replicas{namespace=\"bsp\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PCQ Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "PCQ Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"pcq\"}/kube_deployment_spec_replicas{namespace=\"pcq\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "BAR Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "BAR Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"bar\"}/kube_deployment_spec_replicas{namespace=\"bar\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "AM Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "AM Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"am\"}/kube_deployment_spec_replicas{namespace=\"am\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Adoption Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Adoption Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"adoption\"}/kube_deployment_spec_replicas{namespace=\"adoption\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fees & Pay Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "fees-pay Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"fees-pay\"}/kube_deployment_spec_replicas{namespace=\"fees-pay\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "SSCS Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "SSCS Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"sscs\"}/kube_deployment_spec_replicas{namespace=\"sscs\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "XUI Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "XUI Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"xui\"}/kube_deployment_spec_replicas{namespace=\"xui\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Family Public Law Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "family-public-law Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"family-public-law\"}/kube_deployment_spec_replicas{namespace=\"family-public-law\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "AAC Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "AAC Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"aac\"}/kube_deployment_spec_replicas{namespace=\"aac\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CTSC Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "CTSC Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"ctsc\"}/kube_deployment_spec_replicas{namespace=\"ctsc\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "COH Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "COH Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"coh\"}/kube_deployment_spec_replicas{namespace=\"coh\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ethos Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Ethos Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"ethos\"}/kube_deployment_spec_replicas{namespace=\"ethos\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  },
  {
   "title": "EM Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "Datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "EM Applications Health Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"em\"}/kube_deployment_spec_replicas{namespace=\"em\"} * 100",
       "legendFormat": "{{ deployment }}"
      }
     ]
    }
   ]
  }
 ]
}