{
 "title": "Flux-Helm performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>Flux Performance</span>\n</div>\n\n"
  },
  {
   "title": "Duration of git-to-cluster synchronisation",
   "type": "graph",
   "description": "Duration of all the successful git-to-cluster synchronization",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_daemon_sync_duration_seconds_sum{job=\"flux\"}[5m])) by (success)"
    }
   ]
  },
  {
   "title": "Duration of remote image metadata requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_client_fetch_duration_seconds_sum{job=\"flux\"}[5m])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Duration of image metadata requests (from cache)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flux_registry_fetch_duration_seconds_sum{job=\"flux\"}[5m]))",
     "legendFormat": "Registry fetch"
    }
   ]
  },
  {
   "title": "Number of manifests being synced to cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flux_daemon_sync_manifests" }
   ]
  },
  {
   "title": "General flux sync errors",
   "type": "graph",
   "description": "If this is true then there are some problems with infrastructure or there are manifests parse error or there are manifests with duplicate ids.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flux_daemon_sync_duration_seconds_count{success='false'}[6m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>Helm Operator Performance</span>\n</div>\n\n"
  },
  {
   "title": "HelmOperator Release Queue Length",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(flux_helm_operator_release_queue_length_count)"
    }
   ]
  },
  {
   "title": "Duration of time spent in the job queue before execution",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.25, sum(irate(flux_daemon_queue_duration_seconds_bucket[1m])) by (le)) / 1000)",
     "legendFormat": "P25"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(flux_daemon_queue_duration_seconds_bucket[1m])) by (le)) / 1000)",
     "legendFormat": "P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(flux_daemon_queue_duration_seconds_bucket[1m])) by (le)) / 1000)",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Duration of job execution, in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.25, sum(irate(flux_daemon_job_duration_seconds_bucket{success=\"true\"}[1m])) by (success,le)) / 1000)",
     "legendFormat": "P25"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(flux_daemon_job_duration_seconds_bucket{success=\"true\"}[1m])) by (le)) / 1000)",
     "legendFormat": "P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(flux_daemon_job_duration_seconds_bucket{success=\"true\"}[1m])) by (le)) / 1000)",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 43 },
   "content": "<div class=\"dashboard-header text-center\">\n<span> I/O performance </span>\n</div>\n\n"
  },
  {
   "title": "CPU time spent waiting for I/O per node",
   "type": "graph",
   "description": "A high iowait means that we are disk or network bound",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (mode, instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[5m]))"
    }
   ]
  },
  {
   "title": "Percentage disk I/O utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[5m]) * 100"
    }
   ]
  },
  {
   "title": "Number of IOs in progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_disk_io_now" }
   ]
  }
 ]
}