{
 "title": "Kuberhealthy",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "check",
    "query": "label_values(kuberhealthy_check, check)\t"
   }
  ]
 },
 "panels": [
  { "title": "Overall Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(kuberhealthy_check)" }
   ]
  },
  {
   "title": "Kuberhealthy status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(kuberhealthy_running)" }
   ]
  },
  { "title": "Checks Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$check",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "repeat": "check",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(kuberhealthy_check{check=\"$check\"})"
    }
   ]
  },
  {
   "title": "Kuberhealthy Check Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg(kuberhealthy_check) by(check)"
    }
   ]
  },
  {
   "title": "Kuberhealthy History",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 1, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(kuberhealthy_running)", "legendFormat": "Kuberhealthy Running" },
    {
     "expr": "avg(kuberhealthy_cluster_state)",
     "legendFormat": "Cluster State"
    }
   ]
  },
  {
   "title": "Kuberhealthy Check History",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kuberhealthy_check) by(check)"
    }
   ]
  }
 ]
}