{
 "title": "Mailrelay Dashboard",
 "description": "Insight into exim logs for mailrelay",
 "tags": [
  "mailrelay",
  "exim"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "mailrelay-exim-0",
   "type": "graph",
   "description": "Shows the total number of messages processed by the mail relay",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "exim_messages_total{instance=\"10.144.0.21:9636\",job=\"mailrelay-exim\",pod=\"mailrelay-exim-0\", flag=\"arrived\"}",
     "legendFormat": "{{flag}}"
    },
    {
     "expr": "exim_messages_total{instance=\"10.144.0.21:9636\",job=\"mailrelay-exim\",pod=\"mailrelay-exim-0\", flag=\"completed\"}",
     "legendFormat": "{{flag}}"
    },
    {
     "expr": "exim_messages_total{instance=\"10.144.0.21:9636\",job=\"mailrelay-exim\",pod=\"mailrelay-exim-0\", flag=\"delivered\"}",
     "legendFormat": "{{flag}}"
    },
    {
     "expr": "exim_messages_total{instance=\"10.144.0.21:9636\",job=\"mailrelay-exim\",pod=\"mailrelay-exim-0\", flag=\"failed\"}",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "mailrelay-exim-1",
   "type": "graph",
   "description": "Shows the total number of messages processed by the mail relay",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "string", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "exim_messages_total{instance=\"10.144.0.5:9636\",job=\"mailrelay-exim\",pod=\"mailrelay-exim-1\", flag=\"arrived\"}",
     "legendFormat": "{{flag}}"
    },
    {
     "expr": "exim_messages_total{instance=\"10.144.0.5:9636\",job=\"mailrelay-exim\",pod=\"mailrelay-exim-1\", flag=\"completed\"}",
     "legendFormat": "{{flag}}"
    },
    {
     "expr": "exim_messages_total{instance=\"10.144.0.5:9636\",job=\"mailrelay-exim\",pod=\"mailrelay-exim-1\", flag=\"delivered\"}",
     "legendFormat": "{{flag}}"
    },
    {
     "expr": "exim_messages_total{instance=\"10.144.0.5:9636\",job=\"mailrelay-exim\",pod=\"mailrelay-exim-1\", flag=\"failed\"}",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Rejected Messages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(exim_reject_total{instance=\"10.144.0.21:9636\",job=\"mailrelay-exim\",pod=\"mailrelay-exim-0\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(exim_reject_total{instance=\"10.144.0.5:9636\",job=\"mailrelay-exim\",pod=\"mailrelay-exim-1\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mail Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "exim_queue{instance=\"10.144.0.21:9636\", job=\"mailrelay-exim\", pod=\"mailrelay-exim-0\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "exim_queue{instance=\"10.144.0.5:9636\", job=\"mailrelay-exim\", pod=\"mailrelay-exim-1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mailrelay Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "exim_up{instance=\"10.144.0.21:9636\",job=\"mailrelay-exim\",pod=\"mailrelay-exim-0\"}",
     "legendFormat": "{{instance}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Mailrelay Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "exim_up{instance=\"10.144.0.5:9636\",job=\"mailrelay-exim\",pod=\"mailrelay-exim-1\"}",
     "legendFormat": "{{instance}} - {{pod}}"
    }
   ]
  }
 ]
}